// ORCA UI strings — en (default), fa, ru, zh. Loaded before app.js; app.js reads window.ORCA_I18N.
// Rules: every key exists in `en`; other languages fall back to `en` for anything missing.
(function () {
  const en = {
    newChat: 'New chat', searchPh: 'Search conversations', leaderboard: 'Leaderboard', memory: 'Memory', settings: 'Settings', modeDirect: 'Chat', modeSide: 'Compare', modeBattle: 'Battle',
    heroTitle: 'What shall we build today?', tagline: 'Writes, runs, searches and debugs — right on this machine.', stop: 'Stop', plan: 'Plan', inputPh: 'Ask ORCA to do anything… (Shift+Enter for newline)',
    tabTimeline: 'Timeline', tabFiles: 'Files', tabChanges: 'Changes', tabPreview: 'Preview', openFolder: 'Open folder', save: 'Save', restoreAll: 'Restore all', emptyTimeline: 'Tools ORCA runs will be logged here.', footnote: 'ORCA can make mistakes — verify important output.',
    thoughts: 'Reasoning', copy: 'Copy', copied: 'Copied', regen: 'Retry', edit: 'Edit', modelA: 'Model A', modelB: 'Model B', voteA: 'A is better', voteB: 'B is better', tie: 'Tie', both: 'Both bad', revealed: 'Models:', approveQ: 'Allow this action?', allow: 'Allow', allowAll: 'Allow all', deny: 'Deny', risk: { high: 'HIGH RISK', medium: 'medium', low: 'low' },
    planGo: 'Execute', planEdit: 'Revise plan', today: 'Today', yesterday: 'Yesterday', week: 'This week', older: 'Older', pinned: 'Pinned', noChats: 'No chats yet', stopped: 'Stopped', restore: 'Restore', restored: 'Restored', created: 'new', deleted: 'deleted', modified: 'modified', saved: 'Saved', delChat: 'Delete this chat?', running: 'A run is in progress — stop it first', thinking: 'thinking', step: 'step',
    tier: { strong: 'strong', fast: 'fast', backup: 'backup', custom: 'custom', auto: 'all-purpose' }, winner: 'winner', tasks: 'Task checklist', subagent: 'sub-agent', uploading: 'Uploading…', imgHint: 'Images are read with OCR (en/fa/ru/zh); enable a vision model in Settings for full image understanding.', dropHere: 'Drop to attach', outputs: 'Outputs', compacted: 'Conversation compacted', moreSteps: (n) => `${n} more steps…`, lessSteps: 'less', download: 'Download', openInPanel: 'Open in panel', exported: 'Exported', renamed: 'Renamed', rename: 'New name:', pin: 'Pin', unpin: 'Unpin', shortcuts: 'Shortcuts', theme: 'Theme', cmdPh: 'Type a command or search chats…', actions: 'Actions', chats: 'Chats', scrollBottom: 'Bottom', railT: 'Toggle chat sidebar', panelT: 'Toggle side panel',
    sugs: [['globe', 'Web research', "Find today's top AI news and summarize with sources"], ['code', 'Build a project', 'Build a To-Do app in HTML/CSS/JS in folder todo and run its tests'], ['download', 'Social downloader', "Find today's 5 trending TikTok videos and download them"], ['image', 'Generate an image', 'Create a minimal flat logo for a café called "Nilo", blue palette'], ['terminal', 'Data analysis', 'Create a sample sales CSV and compute stats plus an ASCII chart with code'], ['sparkle', 'System', "Report this machine's specs, disk space and Node/Python versions"]],
    // updates / cloud
    upd: { available: (v) => `ORCA ${v} is available`, notes: 'What\'s new', download: 'Download update', downloading: 'Downloading…', ready: 'Update downloaded', restart: 'Restart & install', later: 'Later', skip: 'Skip this version', upToDate: 'You\'re on the latest version', check: 'Check for updates', checking: 'Checking…', error: 'Update check failed', must: 'This version is no longer supported — please update to continue.', manual: 'Open download page', channel: 'Channel', installed: 'Installed', latest: 'Latest', cloud: 'ORCA Cloud', cloudOk: 'connected', cloudDown: 'unreachable — built-in models paused, your own keys still work', cloudOff: 'not configured', notice: 'Notice', gateway: 'Built-in models are served through ORCA Cloud. No keys are stored in the app; add your own providers below if you like.' },
    st: { general: 'General', appearance: 'Appearance', models: 'Models', agent: 'Agent', data: 'Data', updates: 'Updates', theme: 'Theme', dark: 'Dark', light: 'Light', system: 'System', accent: 'Accent color', fontSize: 'Text size', density: 'Density', comfortable: 'Comfortable', compact: 'Compact', lang: 'Interface language', sendKey: 'Send key', enter: 'Enter', ctrlEnter: 'Ctrl+Enter', showReasoning: 'Show reasoning while generating', notifications: 'System notification when window is inactive', sound: 'Sound on completion', keys: 'Your API keys (optional)', keysDesc: 'Keys are stored only on this device and are used for the providers you add here.', modelsList: 'Available models', defaultModel: 'Default model', addModel: 'Add model', provider: 'Provider', modelId: 'Model id', label: 'Label', add: 'Add', loadOR: 'OpenRouter list', test: 'Test', autonomy: 'Autonomy level', autoAsk: 'Ask', autoAuto: 'Auto', autoYolo: 'Full auto', maxSteps: 'Max steps per run', temperature: 'Creativity (temperature)', effort: 'Reasoning effort', low: 'Low', medium: 'Medium', high: 'High', rules: 'Your rules', rulesDesc: 'Standing instructions for ORCA, like Cursor rules. (e.g. always use TypeScript, never add comments)', persona: 'About you', personaDesc: 'Name, role, preferences — so ORCA knows you.', shellTimeout: 'Shell command timeout (s)', vision: 'Vision model (seeing images)', visionDesc: 'Built-in models are text-only and read images via OCR. Add an OpenRouter key (has free vision models) or any OpenAI-compatible vision endpoint for full image understanding.', imageGen: 'Image generation', imageGenDesc: 'Works without a key (free provider). For higher quality: OpenAI (gpt-image) or OpenRouter (Gemini image).', videoGen: 'Video generation', videoGenDesc: 'Without a key: AI key-frames + ffmpeg animation. With a Replicate or fal.ai key: real text-to-video models (Wan, Kling, Hailuo, Veo…).', social: 'Social media downloader', socialDesc: 'Login-walled content (Instagram Explore/stories, some X posts) needs browser cookies: browser name (chrome/firefox/edge) or a cookies.txt path.', apiKey: 'API key', baseUrl: 'Base URL', free: 'free/built-in', workspace: 'Workspace folder', dataDir: 'Data folder', exportChat: 'Export this chat', exportAll: 'Backup all chats (JSON)', importAll: 'Restore backup', clearAll: 'Delete all chats', clearConfirm: 'Delete ALL chats? This cannot be undone.', stats: 'Stats', statChats: 'chats', statMsgs: 'messages', statCk: 'checkpoints', version: 'Version', shortcuts: 'Keyboard shortcuts', autoUpdate: 'Check for updates automatically', github: 'Source & releases on GitHub' },
  };

  const fa = {
    newChat: 'گفتگوی جدید', searchPh: 'جست‌وجو در گفتگوها', leaderboard: 'رتبه‌بندی', memory: 'حافظه', settings: 'تنظیمات', modeDirect: 'گفتگو', modeSide: 'مقایسه', modeBattle: 'نبرد',
    heroTitle: 'امروز چه چیزی بسازیم؟', tagline: 'می‌نویسد، اجرا می‌کند، جست‌وجو می‌کند، اشکال‌زدایی می‌کند — روی همین سیستم.', stop: 'توقف', plan: 'نقشه', inputPh: 'از ORCA بخواه هر کاری انجام دهد… (Shift+Enter برای خط جدید)',
    tabTimeline: 'تایم‌لاین', tabFiles: 'فایل‌ها', tabChanges: 'تغییرات', tabPreview: 'پیش‌نمایش', openFolder: 'باز کردن پوشه', save: 'ذخیره', restoreAll: 'بازگردانی همه', emptyTimeline: 'ابزارهایی که ORCA اجرا می‌کند این‌جا ثبت می‌شوند.', footnote: 'ORCA می‌تواند اشتباه کند — خروجی‌های مهم را بررسی کنید.',
    thoughts: 'استدلال', copy: 'کپی', copied: 'کپی شد', regen: 'دوباره', edit: 'ویرایش', modelA: 'مدل A', modelB: 'مدل B', voteA: 'A بهتر بود', voteB: 'B بهتر بود', tie: 'مساوی', both: 'هر دو ضعیف', revealed: 'مدل‌ها:', approveQ: 'اجازهٔ اجرا؟', allow: 'اجازه بده', allowAll: 'همه را اجازه بده', deny: 'رد کن', risk: { high: 'خطر بالا', medium: 'متوسط', low: 'کم' },
    planGo: 'اجرا کن', planEdit: 'اصلاح نقشه', today: 'امروز', yesterday: 'دیروز', week: 'این هفته', older: 'قدیمی‌تر', pinned: 'سنجاق‌شده', noChats: 'هنوز گفتگویی نیست', stopped: 'متوقف شد', restore: 'بازگردانی', restored: 'بازگردانی شد', created: 'جدید', deleted: 'حذف', modified: 'تغییر', saved: 'ذخیره شد', delChat: 'این گفتگو حذف شود؟', running: 'یک اجرا در حال انجام است — اول توقف بزن', thinking: 'در حال فکر کردن', step: 'مرحله',
    tier: { strong: 'قوی', fast: 'سریع', backup: 'پشتیبان', custom: 'سفارشی', auto: 'همه‌کاره' }, winner: 'برنده', tasks: 'چک‌لیست کار', subagent: 'زیرعامل', uploading: 'در حال آپلود…', imgHint: 'عکس‌ها با OCR (فارسی/انگلیسی/روسی/چینی) خوانده می‌شوند؛ برای درک کامل تصویر، مدل بینایی را در تنظیمات فعال کنید.', dropHere: 'رها کنید تا پیوست شود', outputs: 'خروجی‌ها', compacted: 'گفتگو فشرده شد', moreSteps: (n) => `${n} مرحلهٔ دیگر…`, lessSteps: 'کمتر', download: 'دانلود', openInPanel: 'باز کردن در پنل', exported: 'خروجی گرفته شد', renamed: 'تغییر نام داده شد', rename: 'نام جدید:', pin: 'سنجاق', unpin: 'برداشتن سنجاق', shortcuts: 'میان‌برها', theme: 'تم', cmdPh: 'دستور بنویس یا گفتگوها را جست‌وجو کن…', actions: 'عملیات', chats: 'گفتگوها', scrollBottom: 'پایین', railT: 'نمایش/پنهان‌کردن نوار گفتگوها', panelT: 'نمایش/پنهان‌کردن پنل کناری',
    sugs: [['globe', 'تحقیق وب', 'آخرین اخبار هوش مصنوعی امروز رو پیدا کن و با منبع خلاصه کن'], ['code', 'ساخت پروژه', 'یک اپ To-Do با HTML/CSS/JS بساز، در پوشهٔ todo ذخیره کن و تستش رو اجرا کن'], ['download', 'دانلود از شبکه‌ها', '۵ ویدیوی ترند امروز تیک‌تاک رو پیدا کن و دانلود کن'], ['image', 'تولید تصویر', 'یک لوگوی مینیمال برای کافه‌ای به اسم «نیلو» بساز، سبک فلت، رنگ آبی'], ['terminal', 'تحلیل داده', 'یک CSV نمونهٔ فروش بساز و با کد آمارش را حساب کن و نمودار ASCII بکش'], ['sparkle', 'سیستم', 'مشخصات این سیستم، فضای دیسک و نسخهٔ Node/Python رو گزارش بده']],
    upd: { available: (v) => `نسخهٔ ${v} ORCA آماده است`, notes: 'تازه‌ها', download: 'دانلود به‌روزرسانی', downloading: 'در حال دانلود…', ready: 'به‌روزرسانی دانلود شد', restart: 'راه‌اندازی مجدد و نصب', later: 'بعداً', skip: 'رد کردن این نسخه', upToDate: 'آخرین نسخه را دارید', check: 'بررسی به‌روزرسانی', checking: 'در حال بررسی…', error: 'بررسی به‌روزرسانی ناموفق بود', must: 'این نسخه دیگر پشتیبانی نمی‌شود — برای ادامه به‌روزرسانی کنید.', manual: 'باز کردن صفحهٔ دانلود', channel: 'کانال', installed: 'نصب‌شده', latest: 'آخرین', cloud: 'ابر ORCA', cloudOk: 'متصل', cloudDown: 'در دسترس نیست — مدل‌های داخلی موقتاً متوقف‌اند، کلیدهای خودتان کار می‌کنند', cloudOff: 'پیکربندی نشده', notice: 'اطلاعیه', gateway: 'مدل‌های داخلی از طریق ابر ORCA ارائه می‌شوند. هیچ کلیدی داخل برنامه نیست؛ در صورت تمایل ارائه‌دهنده‌های خودتان را پایین اضافه کنید.' },
    st: { general: 'عمومی', appearance: 'ظاهر', models: 'مدل‌ها', agent: 'عامل', data: 'داده', updates: 'به‌روزرسانی', theme: 'تم', dark: 'تیره', light: 'روشن', system: 'سیستم', accent: 'رنگ اصلی', fontSize: 'اندازهٔ متن', density: 'تراکم', comfortable: 'راحت', compact: 'فشرده', lang: 'زبان رابط', sendKey: 'کلید ارسال', enter: 'Enter', ctrlEnter: 'Ctrl+Enter', showReasoning: 'نمایش استدلال هنگام تولید', notifications: 'اعلان سیستم وقتی پنجره فعال نیست', sound: 'صدای پایان کار', keys: 'کلیدهای API شما (اختیاری)', keysDesc: 'کلیدها فقط روی همین دستگاه ذخیره می‌شوند و برای ارائه‌دهنده‌هایی که این‌جا اضافه می‌کنید استفاده می‌شوند.', modelsList: 'مدل‌های در دسترس', defaultModel: 'مدل پیش‌فرض', addModel: 'افزودن مدل', provider: 'ارائه‌دهنده', modelId: 'شناسهٔ مدل', label: 'نام نمایشی', add: 'افزودن', loadOR: 'لیست OpenRouter', test: 'تست', autonomy: 'سطح خودمختاری', autoAsk: 'با تأیید', autoAuto: 'خودکار', autoYolo: 'کاملاً خودکار', maxSteps: 'حداکثر مراحل هر اجرا', temperature: 'خلاقیت (temperature)', effort: 'عمق تفکر', low: 'کم', medium: 'متوسط', high: 'زیاد', rules: 'قوانین شما', rulesDesc: 'دستورالعمل‌های دائمی برای ORCA؛ مثل قوانین Cursor. (مثلاً: همیشه TypeScript بنویس، کامنت فارسی نگذار)', persona: 'دربارهٔ شما', personaDesc: 'اسم، شغل، ترجیحات — تا ORCA شما را بشناسد.', shellTimeout: 'مهلت دستورات شل (ثانیه)', vision: 'مدل بینایی (دیدن عکس)', visionDesc: 'مدل‌های داخلی متنی‌اند و عکس را فقط با OCR می‌خوانند. با کلید OpenRouter (مدل‌های رایگان دارد) یا هر سرویس سازگار با OpenAI، درک کامل تصویر فعال می‌شود.', imageGen: 'تولید تصویر', imageGenDesc: 'بدون کلید هم کار می‌کند (سرویس رایگان). برای کیفیت بالاتر: OpenAI (gpt-image) یا OpenRouter (Gemini image).', videoGen: 'تولید ویدیو', videoGenDesc: 'بدون کلید: فریم‌های AI + انیمیشن ffmpeg. با کلید Replicate یا fal.ai: مدل‌های واقعی متن‌به‌ویدیو (Wan، Kling، Hailuo، Veo…).', social: 'دانلودر شبکه‌های اجتماعی', socialDesc: 'برای محتوای نیازمند لاگین (Explore/استوری اینستاگرام، برخی پست‌های X) کوکی مرورگر لازم است: نام مرورگر (chrome/firefox/edge) یا مسیر فایل cookies.txt.', apiKey: 'کلید API', baseUrl: 'آدرس پایه', free: 'رایگان/داخلی', workspace: 'پوشهٔ کاری', dataDir: 'پوشهٔ داده', exportChat: 'خروجی این گفتگو', exportAll: 'پشتیبان از همهٔ گفتگوها (JSON)', importAll: 'بازیابی پشتیبان', clearAll: 'حذف همهٔ گفتگوها', clearConfirm: 'همهٔ گفتگوها حذف شوند؟ این عمل برگشت‌ناپذیر است.', stats: 'آمار', statChats: 'گفتگو', statMsgs: 'پیام', statCk: 'نقطهٔ بازگشت', version: 'نسخه', shortcuts: 'میان‌برهای صفحه‌کلید', autoUpdate: 'بررسی خودکار به‌روزرسانی', github: 'سورس و نسخه‌ها در GitHub' },
  };

  const ru = {
    newChat: 'Новый чат', searchPh: 'Поиск по чатам', leaderboard: 'Рейтинг', memory: 'Память', settings: 'Настройки', modeDirect: 'Чат', modeSide: 'Сравнение', modeBattle: 'Битва',
    heroTitle: 'Что создадим сегодня?', tagline: 'Пишет, запускает, ищет и отлаживает — прямо на этом компьютере.', stop: 'Стоп', plan: 'План', inputPh: 'Попросите ORCA сделать что угодно… (Shift+Enter — новая строка)',
    tabTimeline: 'Хроника', tabFiles: 'Файлы', tabChanges: 'Изменения', tabPreview: 'Предпросмотр', openFolder: 'Открыть папку', save: 'Сохранить', restoreAll: 'Восстановить всё', emptyTimeline: 'Здесь будут инструменты, которые запускает ORCA.', footnote: 'ORCA может ошибаться — проверяйте важные результаты.',
    thoughts: 'Рассуждение', copy: 'Копировать', copied: 'Скопировано', regen: 'Повторить', edit: 'Изменить', modelA: 'Модель A', modelB: 'Модель B', voteA: 'A лучше', voteB: 'B лучше', tie: 'Ничья', both: 'Обе плохи', revealed: 'Модели:', approveQ: 'Разрешить это действие?', allow: 'Разрешить', allowAll: 'Разрешить всё', deny: 'Отклонить', risk: { high: 'ВЫСОКИЙ РИСК', medium: 'средний', low: 'низкий' },
    planGo: 'Выполнить', planEdit: 'Изменить план', today: 'Сегодня', yesterday: 'Вчера', week: 'На этой неделе', older: 'Раньше', pinned: 'Закреплённые', noChats: 'Чатов пока нет', stopped: 'Остановлено', restore: 'Восстановить', restored: 'Восстановлено', created: 'новый', deleted: 'удалён', modified: 'изменён', saved: 'Сохранено', delChat: 'Удалить этот чат?', running: 'Идёт выполнение — сначала остановите', thinking: 'думает', step: 'шаг',
    tier: { strong: 'сильная', fast: 'быстрая', backup: 'резервная', custom: 'своя', auto: 'универсальная' }, winner: 'победитель', tasks: 'Список задач', subagent: 'субагент', uploading: 'Загрузка…', imgHint: 'Изображения читаются через OCR (en/fa/ru/zh); для полного понимания включите модель зрения в настройках.', dropHere: 'Отпустите, чтобы прикрепить', outputs: 'Результаты', compacted: 'Диалог сжат', moreSteps: (n) => `ещё ${n} шагов…`, lessSteps: 'меньше', download: 'Скачать', openInPanel: 'Открыть в панели', exported: 'Экспортировано', renamed: 'Переименовано', rename: 'Новое имя:', pin: 'Закрепить', unpin: 'Открепить', shortcuts: 'Горячие клавиши', theme: 'Тема', cmdPh: 'Введите команду или найдите чат…', actions: 'Действия', chats: 'Чаты', scrollBottom: 'Вниз', railT: 'Показать/скрыть список чатов', panelT: 'Показать/скрыть боковую панель',
    sugs: [['globe', 'Веб-исследование', 'Найди главные новости ИИ за сегодня и кратко изложи с источниками'], ['code', 'Создать проект', 'Сделай To-Do приложение на HTML/CSS/JS в папке todo и запусти его тесты'], ['download', 'Загрузчик соцсетей', 'Найди 5 трендовых видео TikTok за сегодня и скачай их'], ['image', 'Сгенерировать картинку', 'Создай минималистичный плоский логотип для кафе «Nilo», синяя палитра'], ['terminal', 'Анализ данных', 'Создай пример CSV с продажами, посчитай статистику и нарисуй ASCII-график кодом'], ['sparkle', 'Система', 'Покажи характеристики этого компьютера, место на диске и версии Node/Python']],
    upd: { available: (v) => `Доступна версия ORCA ${v}`, notes: 'Что нового', download: 'Скачать обновление', downloading: 'Загрузка…', ready: 'Обновление загружено', restart: 'Перезапустить и установить', later: 'Позже', skip: 'Пропустить эту версию', upToDate: 'У вас последняя версия', check: 'Проверить обновления', checking: 'Проверка…', error: 'Не удалось проверить обновления', must: 'Эта версия больше не поддерживается — обновитесь, чтобы продолжить.', manual: 'Открыть страницу загрузки', channel: 'Канал', installed: 'Установлена', latest: 'Последняя', cloud: 'ORCA Cloud', cloudOk: 'подключено', cloudDown: 'недоступно — встроенные модели приостановлены, ваши ключи работают', cloudOff: 'не настроено', notice: 'Уведомление', gateway: 'Встроенные модели работают через ORCA Cloud. В приложении нет ключей; при желании добавьте своих провайдеров ниже.' },
    st: { general: 'Общие', appearance: 'Вид', models: 'Модели', agent: 'Агент', data: 'Данные', updates: 'Обновления', theme: 'Тема', dark: 'Тёмная', light: 'Светлая', system: 'Системная', accent: 'Акцентный цвет', fontSize: 'Размер текста', density: 'Плотность', comfortable: 'Просторно', compact: 'Компактно', lang: 'Язык интерфейса', sendKey: 'Клавиша отправки', enter: 'Enter', ctrlEnter: 'Ctrl+Enter', showReasoning: 'Показывать рассуждение во время генерации', notifications: 'Системное уведомление, когда окно неактивно', sound: 'Звук по завершении', keys: 'Ваши API-ключи (необязательно)', keysDesc: 'Ключи хранятся только на этом устройстве и используются для провайдеров, которых вы добавите здесь.', modelsList: 'Доступные модели', defaultModel: 'Модель по умолчанию', addModel: 'Добавить модель', provider: 'Провайдер', modelId: 'ID модели', label: 'Название', add: 'Добавить', loadOR: 'Список OpenRouter', test: 'Тест', autonomy: 'Уровень автономии', autoAsk: 'Спрашивать', autoAuto: 'Авто', autoYolo: 'Полный авто', maxSteps: 'Макс. шагов за запуск', temperature: 'Креативность (temperature)', effort: 'Глубина рассуждений', low: 'Низкая', medium: 'Средняя', high: 'Высокая', rules: 'Ваши правила', rulesDesc: 'Постоянные инструкции для ORCA, как правила Cursor (например: всегда TypeScript, без комментариев).', persona: 'О вас', personaDesc: 'Имя, роль, предпочтения — чтобы ORCA вас знала.', shellTimeout: 'Таймаут команд оболочки (с)', vision: 'Модель зрения (просмотр изображений)', visionDesc: 'Встроенные модели текстовые и читают изображения через OCR. Добавьте ключ OpenRouter (есть бесплатные модели зрения) или любой OpenAI-совместимый эндпоинт для полного понимания изображений.', imageGen: 'Генерация изображений', imageGenDesc: 'Работает без ключа (бесплатный провайдер). Для лучшего качества: OpenAI (gpt-image) или OpenRouter (Gemini image).', videoGen: 'Генерация видео', videoGenDesc: 'Без ключа: ИИ-кадры + анимация ffmpeg. С ключом Replicate или fal.ai: настоящие text-to-video модели (Wan, Kling, Hailuo, Veo…).', social: 'Загрузчик соцсетей', socialDesc: 'Для контента за логином (Instagram Explore/истории, некоторые посты X) нужны cookies браузера: имя браузера (chrome/firefox/edge) или путь к cookies.txt.', apiKey: 'API-ключ', baseUrl: 'Базовый URL', free: 'бесплатно/встроено', workspace: 'Рабочая папка', dataDir: 'Папка данных', exportChat: 'Экспорт этого чата', exportAll: 'Резервная копия всех чатов (JSON)', importAll: 'Восстановить копию', clearAll: 'Удалить все чаты', clearConfirm: 'Удалить ВСЕ чаты? Это нельзя отменить.', stats: 'Статистика', statChats: 'чатов', statMsgs: 'сообщений', statCk: 'контрольных точек', version: 'Версия', shortcuts: 'Горячие клавиши', autoUpdate: 'Проверять обновления автоматически', github: 'Исходники и релизы на GitHub' },
  };

  const zh = {
    newChat: '新对话', searchPh: '搜索对话', leaderboard: '排行榜', memory: '记忆', settings: '设置', modeDirect: '对话', modeSide: '对比', modeBattle: '对战',
    heroTitle: '今天想做点什么？', tagline: '编写、运行、搜索、调试 — 就在这台电脑上。', stop: '停止', plan: '计划', inputPh: '让 ORCA 做任何事… (Shift+Enter 换行)',
    tabTimeline: '时间线', tabFiles: '文件', tabChanges: '更改', tabPreview: '预览', openFolder: '打开文件夹', save: '保存', restoreAll: '全部还原', emptyTimeline: 'ORCA 运行的工具会记录在这里。', footnote: 'ORCA 可能会出错 — 请核对重要输出。',
    thoughts: '推理', copy: '复制', copied: '已复制', regen: '重试', edit: '编辑', modelA: '模型 A', modelB: '模型 B', voteA: 'A 更好', voteB: 'B 更好', tie: '平局', both: '都不好', revealed: '模型：', approveQ: '允许此操作？', allow: '允许', allowAll: '全部允许', deny: '拒绝', risk: { high: '高风险', medium: '中', low: '低' },
    planGo: '执行', planEdit: '修改计划', today: '今天', yesterday: '昨天', week: '本周', older: '更早', pinned: '已置顶', noChats: '还没有对话', stopped: '已停止', restore: '还原', restored: '已还原', created: '新建', deleted: '已删除', modified: '已修改', saved: '已保存', delChat: '删除此对话？', running: '有任务正在运行 — 请先停止', thinking: '思考中', step: '步骤',
    tier: { strong: '强', fast: '快', backup: '备用', custom: '自定义', auto: '全能' }, winner: '胜者', tasks: '任务清单', subagent: '子代理', uploading: '上传中…', imgHint: '图片通过 OCR 读取（中/英/波斯/俄）；在设置中启用视觉模型可完整理解图片。', dropHere: '松开以附加', outputs: '输出', compacted: '对话已压缩', moreSteps: (n) => `还有 ${n} 步…`, lessSteps: '收起', download: '下载', openInPanel: '在面板中打开', exported: '已导出', renamed: '已重命名', rename: '新名称：', pin: '置顶', unpin: '取消置顶', shortcuts: '快捷键', theme: '主题', cmdPh: '输入命令或搜索对话…', actions: '操作', chats: '对话', scrollBottom: '到底部', railT: '显示/隐藏对话栏', panelT: '显示/隐藏侧边栏',
    sugs: [['globe', '网络调研', '查找今天最重要的 AI 新闻并附来源总结'], ['code', '构建项目', '用 HTML/CSS/JS 在 todo 文件夹里做一个待办应用并运行测试'], ['download', '社交媒体下载', '找出今天 5 个 TikTok 热门视频并下载'], ['image', '生成图片', '为名为“Nilo”的咖啡馆设计一个极简扁平 logo，蓝色系'], ['terminal', '数据分析', '生成一个示例销售 CSV，用代码计算统计并画 ASCII 图表'], ['sparkle', '系统', '报告这台电脑的配置、磁盘空间和 Node/Python 版本']],
    upd: { available: (v) => `ORCA ${v} 已发布`, notes: '更新内容', download: '下载更新', downloading: '下载中…', ready: '更新已下载', restart: '重启并安装', later: '稍后', skip: '跳过此版本', upToDate: '已是最新版本', check: '检查更新', checking: '检查中…', error: '检查更新失败', must: '此版本已不再支持 — 请更新后继续使用。', manual: '打开下载页面', channel: '渠道', installed: '已安装', latest: '最新', cloud: 'ORCA 云', cloudOk: '已连接', cloudDown: '无法连接 — 内置模型暂停，你自己的密钥仍可用', cloudOff: '未配置', notice: '通知', gateway: '内置模型通过 ORCA 云提供。应用内不保存任何密钥；如需要可在下方添加自己的服务商。' },
    st: { general: '通用', appearance: '外观', models: '模型', agent: '代理', data: '数据', updates: '更新', theme: '主题', dark: '深色', light: '浅色', system: '跟随系统', accent: '主题色', fontSize: '文字大小', density: '密度', comfortable: '宽松', compact: '紧凑', lang: '界面语言', sendKey: '发送键', enter: 'Enter', ctrlEnter: 'Ctrl+Enter', showReasoning: '生成时显示推理', notifications: '窗口不活跃时发送系统通知', sound: '完成时提示音', keys: '你的 API 密钥（可选）', keysDesc: '密钥只保存在本机，用于你在此添加的服务商。', modelsList: '可用模型', defaultModel: '默认模型', addModel: '添加模型', provider: '服务商', modelId: '模型 ID', label: '显示名称', add: '添加', loadOR: 'OpenRouter 列表', test: '测试', autonomy: '自主级别', autoAsk: '询问', autoAuto: '自动', autoYolo: '完全自动', maxSteps: '每次运行最大步数', temperature: '创造性 (temperature)', effort: '推理深度', low: '低', medium: '中', high: '高', rules: '你的规则', rulesDesc: '给 ORCA 的长期指令，类似 Cursor 规则（例如：始终用 TypeScript，不加注释）。', persona: '关于你', personaDesc: '姓名、职业、偏好 — 让 ORCA 了解你。', shellTimeout: 'Shell 命令超时（秒）', vision: '视觉模型（看图）', visionDesc: '内置模型仅支持文本，通过 OCR 读图。添加 OpenRouter 密钥（有免费视觉模型）或任意 OpenAI 兼容视觉端点即可完整理解图片。', imageGen: '图片生成', imageGenDesc: '无需密钥即可使用（免费服务）。更高质量：OpenAI (gpt-image) 或 OpenRouter (Gemini image)。', videoGen: '视频生成', videoGenDesc: '无密钥：AI 关键帧 + ffmpeg 动画。使用 Replicate 或 fal.ai 密钥：真正的文生视频模型（Wan、Kling、Hailuo、Veo…）。', social: '社交媒体下载器', socialDesc: '需要登录的内容（Instagram 探索/快拍、部分 X 帖子）需要浏览器 cookies：浏览器名称 (chrome/firefox/edge) 或 cookies.txt 路径。', apiKey: 'API 密钥', baseUrl: '基础 URL', free: '免费/内置', workspace: '工作区文件夹', dataDir: '数据文件夹', exportChat: '导出此对话', exportAll: '备份所有对话 (JSON)', importAll: '恢复备份', clearAll: '删除所有对话', clearConfirm: '删除全部对话？此操作不可撤销。', stats: '统计', statChats: '对话', statMsgs: '消息', statCk: '检查点', version: '版本', shortcuts: '键盘快捷键', autoUpdate: '自动检查更新', github: 'GitHub 上的源码与发布' },
  };

  window.ORCA_I18N = { en, fa, ru, zh };
  window.ORCA_LANGS = [['en', 'English'], ['fa', 'فارسی'], ['ru', 'Русский'], ['zh', '中文']];
  window.ORCA_RTL = { fa: true };
})();
